### ISSUE TITLE
GCS + Oauth

### ISSUE THREAD

**Issue by degloba** [degloba/svndegloba#177]
com.google.appengine.api.appidentity.AppIdentityServiceFailureException: The AppIdentity service threw an unexpected error. Details: 
	at com.google.appengine.api.appidentity.AppIdentityServiceImpl.handleApplicationError(AppIdentityServiceImpl.java:109)
	at com.google.appengine.api.appidentity.AppIdentityServiceImpl.getAccessTokenUncached(AppIdentityServiceImpl.java:236)
	at com.google.appengine.api.appidentity.AppIdentityServiceImpl.getAccessToken(AppIdentityServiceImpl.java:291)
	at com.google.appengine.tools.cloudstorage.oauth.AppIdentityAccessTokenProvider.getNewAccessToken(AppIdentityAccessTokenProvider.java:22)
	at com.google.appengine.tools.cloudstorage.oauth.AppIdentityOAuthURLFetchService.getToken(AppIdentityOAuthURLFetchService.java:85)
	at com.google.appengine.tools.cloudstorage.oauth.AbstractOAuthURLFetchService$1.call(AbstractOAuthURLFetchService.java:62)
	at com.google.appengine.tools.cloudstorage.oauth.AbstractOAuthURLFetchService$1.call(AbstractOAuthURLFetchService.java:59)
	at com.google.appengine.tools.cloudstorage.RetryHelper.doRetry(RetryHelper.java:108)

**Comment by degloba** [comment]
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/storage/json-api/src/main/java

**Comment by degloba** [comment]
https://cloud.google.com/storage/docs/json_api/v1/json-api-java-samples

**Comment by degloba** [comment]
@Override
  public GetAccessTokenResult getAccessTokenUncached(Iterable<String> scopes) {
    GetAccessTokenRequest.Builder requestBuilder = GetAccessTokenRequest.newBuilder();
    for (String scope : scopes) {
      requestBuilder.addScope(scope);
    }
    if (requestBuilder.getScopeCount() == 0) {
      throw new AppIdentityServiceFailureException("No scopes specified.");
    }
    GetAccessTokenResponse.Builder responseBuilder = GetAccessTokenResponse.newBuilder();
    try {
      responseBuilder.mergeFrom(
          ApiProxy.makeSyncCall(
              getAccessTokenPackageName(), GET_ACCESS_TOKEN_METHOD_NAME,
              requestBuilder.build().toByteArray()));
    } catch (ApiProxy.ApplicationException e) {
      handleApplicationError(e);
    } catch (InvalidProtocolBufferException e) {
      throw new AppIdentityServiceFailureException(e.getMessage());
    }

    GetAccessTokenResponse response = responseBuilder.build();
    return new GetAccessTokenResult(response.getAccessToken(),
                                    new Date(response.getExpirationTime() * 1000));
  }
