### ISSUE TITLE
No qualifying bean of type [com.degloba.domain.EntityRepository] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency.

### ISSUE THREAD

**Issue by degloba** [degloba/svndegloba#80]
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.degloba.domain.EntityRepository] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}:
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.degloba.domain.EntityRepository] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1301)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1047)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)

**Comment by degloba** [comment]
http://stackoverflow.com/questions/22301426/no-qualifying-bean-of-type-javax-persistence-entitymanager

The EntityManager interface belongs to JPA and is implemented by JPA providers (such as Eclipse), not Spring, and it has its own injection annotation: @PersistenceContext. EntityManager objects are transaction-scoped and should not be exposed as beans as you're doing. Instead, either use the JPA annotation to inject the EntityManager:

@PersistenceContext
EntityManager em;
or, since it looks like you're trying to use Spring repositories, inject the repository instead:

@Autowired
PersonRepository pr;
