### ISSUE TITLE
Error Autowiring EntityRepositoryJpa

### ISSUE THREAD

**Issue by degloba** [degloba/svndegloba#95]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'finder': Injection of persistence dependencies failed; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [com.degloba.persistence.jpa.EntityRepositoryJpa] for bean with name 'repository' defined in class path resource [META-INF/spring/configurationContext.xml]; nested exception is java.lang.ClassNotFoundException: com.degloba.persistence.jpa.EntityRepositoryJpa:
java.lang.ClassNotFoundException: com.degloba.persistence.jpa.EntityRepositoryJpa
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:199)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:249)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:395)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1349)
	at org.springframework.beans.factory.support.AbstractBeanFactory.access$000(AbstractBeanFactory.java:111)
	at org.springframework.beans.factory.support.AbstractBeanFactory$4.run(AbstractBeanFactory.java:1315)

**Comment by degloba** [comment]
1.- Posar autowire="byType"

<bean id="application" class="com.degloba.organisation.application.impl.OrganisationApplicationImpl" autowire="byType">
		  
	</bean>   

2.- Eliminar @Inject

public class OrganisationApplicationImpl implements OrganisationService {

    //@Inject
    private EntityRepository repository;
